sudo: required

language: node_js

node_js:
  - "7.10"

notifications:
  email: false

addons:
  postgresql: "9.4"

env:
  DISABLE_SEBACON=true db_user=postgres db_password=postgres environment=development ENABLE_EMAIL_SENDING=false

cache:
  directories:
    - frontend/elm-stuff/build-artifacts
    - sysconfcpus

before_install:
  - sudo apt-get install language-pack-fi
  - sudo /etc/init.d/postgresql stop
  - sudo /etc/init.d/postgresql start 9.4
install:
  - npm install -g elm@0.19.0
  - npm install -g elm-test
  - npm install

before_script:
  - psql -c "create collation fi_FI (locale='fi_FI.UTF-8');" -U postgres
  - psql -c "create database \"tradenomiitti-test\" LC_COLLATE='fi_FI.UTF-8' LC_CTYPE='fi_FI.UTF-8' template=template0;" -U postgres
  - psql -c "create database \"tradenomiitti\" LC_COLLATE='fi_FI.UTF-8' LC_CTYPE='fi_FI.UTF-8' template=template0;" -U postgres
  - cp conf/example-assets/* conf/assets
  - npm run compilelocal
script:
  - npm run lint
  - npm run test
  - npm run testFrontend
