
exports.up = function(knex, Promise) {
  return knex.schema.createTable('special_skills', function (table) {
    table.increments('id');
    table.string('category');
    table.string('title').unique();
  }).then(() => {
    const skills = {
      'Ammatillinen osaaminen': [
        'Asiakkuuksien johtaminen',
        'Back-end',
        'Bloggaus',
        'Brand management',
        'Budjetointi',
        'Business intelligence',
        'CRM',
        'Datan analysointi',
        'Digitalisaatio',
        'Esiintymistaidot',
        'Esimies',
        'Front-end',
        'Full-stack',
        'Hakukoneoptimointi',
        'HR',
        'Johtaminen',
        'Kvalitatiivinen tutkimus',
        'Kvantitatiivinen tutkimus',
        'Mainonta',
        'Markkinatutkimus',
        'Markkinointi',
        'Markkinointistrategia',
        'Markkinointiviestintä',
        'Myynti',
        'Neuvottelu',
        'Palvelumuotoilu',
        'Projektinhallinta',
        'Rahoitus',
        'Ryhmätyö',
        'SEM',
        'SEO',
        'Sosiaalinen media',
        'Strateginen johtaminen',
        'Suoramarkkinointi',
        'Tapahtumamarkkinointi',
        'Tapahtumien järjestäminen',
        'Tuoteomistajuus',
        'Tutkimus',
        'UI',
        'UX',
        'Verkostoituminen',
        'Videotuotanto',
        'Viestintä',
        'Viestintästrategia',
        'Vloggaus',
        'Web design',
        'Yrittäjyys',
        'Yrityskehitys',
      ],
      'Ohjelmat & sovellukset': [
        'Abode InDesgin',
        'Aditro',
        'Adobe Creative Cloud',
        'Adobe Illustrator',
        'Asteri',
        'Basware',
        'Comms Client Pro',
        'Contactor',
        'Digium',
        'Econet',
        'Effica',
        'ELBITHR',
        'EmCe',
        'ePressi',
        'eTasku',
        'Facebook',
        'Facebook Display',
        'Fivaldi',
        'Google AdWords',
        'Google analytics',
        'Heeros',
        'Heimo HR',
        'Instagram',
        'JIRA',
        'Lemonsoft',
        'LinkedIn',
        'Maestro',
        'MATLAB',
        'Mepco HRM',
        'Microsoft Excel',
        'Microsoft Office',
        'Microsoft PowerPoint',
        'Microsoft Sharepoint',
        'Microsoft Word',
        'NetBaron',
        'Netvisor',
        'Netvisor HRM',
        'Njorf',
        'Nova',
        'Opera',
        'Opus Capita',
        'Orbis',
        'Personec W',
        'Postiviidakko',
        'Prezi',
        'ProCountor',
        'Readsoft',
        'Recrur',
        'SaaS',
        'SAP',
        'Slideshare',
        'Snapchat',
        'Solaforce',
        'SPSS',
        'SurveyPal',
        'Talgraf',
        'Tiima',
        'Tikon',
        'Twitter',
        'TyövuoroVelho',
        'Visma',
        'Webropol',
        'Western',
      ],
      Julkaisualustat: [
        'Ambientia Content Manager',
        'BigCommerce',
        'Blogger',
        'Concrete5',
        'Crasman Stage',
        'Demandware',
        'Directo',
        'Drupal',
        'Drupal Commerce',
        'ePages',
        'EPiServer',
        'EPiServer Commerce',
        'Experience Manager',
        'Expression Engine',
        'eZ Publish',
        'InfoWeb',
        'Joomla',
        'Kotisivukone',
        'Liferay',
        'Magento',
        'Magento Enterprise',
        'Movable Type',
        'MyCashflow',
        'NetCommunity',
        'Open Atrium',
        'OpenCart',
        'Oracle Commerce',
        'osCommerce',
        'Plone',
        'Posterous',
        'PrestaShop',
        'Prime',
        'Processwire',
        'SDL Tridion',
        'SharePoint',
        'Shopify',
        'SilverStripe',
        'Sitecore',
        'Sitefinity',
        'Sivuviidakko',
        'Stato',
        'TotalDynamic',
        'Tumblr',
        'Typepad',
        'Typo3',
        'Umbraco',
        'Vilkas',
        'VirtueMart',
        'Vizrt Online Suite',
        'Volusion',
        'WebCenter Suite',
        'WooCommerce',
        'Wordpress',
        'Yahoo Store',
        'Zen Cart',
      ],
      Yleiset: [
        'Hyvinvointi',
        'Koulutus',
        'Kulttuuri',
        'Lapset ja nuoret',
        'Luonto',
        'Matkailu',
        'Muoti',
        'Politiikka',
        'Ruoka',
        'Taide',
        'Talous',
        'Tasa-arvo',
        'Tekniikka',
        'Teollisuus',
        'Terveys',
        'Tiede',
        'Työelämä',
        'Urheilu',
        'Yhteiskunta',
      ],
    };
    const skillObjectLists = Object.keys(skills).map(key => {
      return skills[key].map(title => ({ category: key, title }))
    })

    const skillObjects = [].concat.apply([], skillObjectLists);
    return knex('special_skills').insert(skillObjects);
  })
};

exports.down = function(knex, Promise) {
  return knex.schema.dropTable('special_skills');
};
