---
- hosts: [ dev, qa, prod ]
  remote_user: ubuntu
  become: yes
  tasks:
    - name: copy node repo key
      copy: src=nodesource.gpg.key dest=/var/cache/nodesource.gpg.key

    - name: install node repo key
      apt_key: file=/var/cache/nodesource.gpg.key state=present

    - name: install node repo
      apt_repository:
        repo: deb https://deb.nodesource.com/node_7.x xenial main

    - name: install system dependencies
      apt: pkg={{item}} state=present
      with_items:
        - postgresql
        - nodejs
        - git
        - python-psycopg2
        - graphicsmagick


    - name: install nginx basic auth password file
      template: src=passwd dest=/etc/nginx/passwd
      notify:
        - restart nginx

    - name: install nginx.conf
      template: src=nginx.conf dest=/etc/nginx/nginx.conf
      notify:
        - restart nginx
      
    - name: create database user
      become_user: postgres
      postgresql_user:
        name : "{{db_user}}"
        password : "{{db_password}}"

    - name: create database
      become_user: postgres
      postgresql_db:
        name: tradenomiitti
        owner: "{{db_user}}"

    - name: ensure base services are running
      service: name={{item}} state=started enabled=yes
      with_items: [ nginx, postgresql ]


    # Set up deployment by git push env master
    - name: make base directories
      file: path={{item}} state=directory mode=0755 owner=ubuntu
      with_items: [ /srv, /srv/checkout ]
    - name: create bare git repo
      become: no
      command: git --bare init tradenomiitti.git
      args:
        chdir: /srv
        creates: /srv/tradenomiitti.git

    - name: do initial clone
      become: no
      command: git clone /srv/tradenomiitti.git
      args:
        chdir: /srv/checkout
        creates: /srv/checkout/tradenomiitti

    - name: add deploy hook
      copy: src=deploy.sh dest=/srv/tradenomiitti.git/hooks/post-receive mode=0755
    
    # database configuration
    - name: database configuration
      template: src=app.json dest=/srv/app.json 
    
    # create folders for static files and user images
    - name: static folder creation
      file: path=/srv/static/images state=directory mode=0755 owner=ubuntu

    # upload static images (logos etc.)
    - name: upload images
      copy: src=assets/{{ item }} dest=/srv/static/{{ item }}
      with_items:
        - main_logo.svg
        - email_logo.png
        - footer_logo.png
        - home_image.jpg

    # upload custom font files
    - name: upload fonts
      copy: src=assets/{{ item }} dest=/srv/static/{{ item }}
      with_items: "{{ custom_font_files }}"
        # - MundoSansStd.otf
        # - MundoSansStd-LightItalic.otf

    - name: upload google analytics id
      template: src=google-analytics-id dest=/srv/static/google-analytics-id

  handlers:
    - name: restart nginx
      service: name=nginx state=restarted
