---
- name: Warn about using pip
  debug:
    msg: "Warning: installing letsencrypt using pip is not officially supported and may break with upgrades."

- name: Install depends
  package: name={{ item }} state=present
  become: yes
  with_items: "{{ letsencrypt_depends | default([]) }}"
  tags: install

- name: Install virtualenv
  package: name={{ item }} state=present
  become: yes
  with_items: "{{ virtualenv_package_name | default([]) }}"
  tags: install

- name: Install python depends
  pip:
    virtualenv: "{{ letsencrypt_venv }}"
    virtualenv_site_packages: no
    name: "{{ item }}"
    state: latest
    virtualenv_python: python2
  become: yes
  with_items:
    - setuptools
    - pip
  tags: install

- name: Install pycparser
  # https://community.letsencrypt.org/t/certbot-auto-fails-while-setting-up-virtual-environment-complains-about-package-hashes/20529/22
  pip: virtualenv="{{ letsencrypt_venv }}" virtualenv_site_packages=no name=pycparser version=2.13 state=present virtualenv_python=python2
  become: yes
  tags: install
  when: ansible_os_family == "RedHat"

- name: More python depends
  pip:
    virtualenv: "{{ letsencrypt_venv }}"
    virtualenv_site_packages: no
    name: letsencrypt
    state: latest
  become: yes
  tags: install
